export {
  ensureAgentInitialized,
  getAgent,
  getAgentSession,
  hasActiveSession,
  activateSession,
  newSession,
  renameSession,
  deleteSession,
  listAllSessions,
  newGlobalSession,
  subscribeToActiveSession,
  getSessionId,
  getSessionName,
  setSessionName,
  getSessionMessages,
  getSessionFile,
  getContextUsage,
  getActiveCwd,
  setModel,
  compact,
  setAutoCompaction,
  abort,
  exportSession,
  prompt,
  // Project related (defined in pool.ts)
  activateProject,
  getActiveProjectPath,
  registerProject,
  unregisterProject,
  renameProjectByPath,
} from './pool.js';
export { getSessionManager, listSessions } from './manager.js';